// Mock data for the expense tracker

export const categories = [
  { id: 'food', name: 'Food & Dining', code: '7012' },
  { id: 'office', name: 'Office Expenses', code: '4053' },
  { id: 'fuel', name: 'Fuel & Commute', code: '3242' },
  { id: 'utilities', name: 'Utilities', code: '4900' },
  { id: 'software', name: 'Software & Subscriptions', code: '5045' },
  { id: 'marketing', name: 'Marketing & Advertising', code: '7311' },
  { id: 'travel', name: 'Travel & Accommodation', code: '4722' },
  { id: 'insurance', name: 'Insurance', code: '6300' },
]

export const expenses = [
  {
    id: '1',
    date: '2025-01-24',
    description: "McDonald's",
    category: 'food',
    amount: 45.99,
    paymentMethod: 'Debit Card',
    aiSuggested: true,
    confidence: 95,
    status: 'paid',
  },
  {
    id: '2',
    date: '2025-01-23',
    description: 'Staples - Office Supplies',
    category: 'office',
    amount: 234.5,
    paymentMethod: 'Credit Card',
    aiSuggested: true,
    confidence: 92,
    status: 'pending',
  },
  {
    id: '3',
    date: '2025-01-22',
    description: 'Shell Gas Station',
    category: 'fuel',
    amount: 78.0,
    paymentMethod: 'Credit Card',
    aiSuggested: true,
    confidence: 98,
    status: 'paid',
  },
  {
    id: '4',
    date: '2025-01-21',
    description: 'Adobe Creative Cloud',
    category: 'software',
    amount: 54.99,
    paymentMethod: 'Credit Card',
    aiSuggested: false,
    confidence: 100,
    status: 'paid',
  },
  {
    id: '5',
    date: '2025-01-20',
    description: 'Hydro One - Electricity',
    category: 'utilities',
    amount: 189.45,
    paymentMethod: 'Bank Transfer',
    aiSuggested: true,
    confidence: 88,
    status: 'overdue',
  },
  {
    id: '6',
    date: '2025-01-19',
    description: 'Google Ads Campaign',
    category: 'marketing',
    amount: 500.0,
    paymentMethod: 'Credit Card',
    aiSuggested: true,
    confidence: 91,
    status: 'pending',
  },
  {
    id: '7',
    date: '2025-01-18',
    description: 'Marriott Hotel - Toronto',
    category: 'travel',
    amount: 325.0,
    paymentMethod: 'Credit Card',
    aiSuggested: true,
    confidence: 94,
    status: 'paid',
  },
  {
    id: '8',
    date: '2025-01-17',
    description: 'Tim Hortons',
    category: 'food',
    amount: 12.5,
    paymentMethod: 'Debit Card',
    aiSuggested: true,
    confidence: 97,
    status: 'paid',
  },
]

export const income = [
  {
    id: '1',
    date: '2025-01-15',
    description: 'Client Payment - ABC Corp',
    amount: 5000.0,
    source: 'Invoice',
  },
  {
    id: '2',
    date: '2025-01-10',
    description: 'Consulting Fee - XYZ Ltd',
    amount: 2500.0,
    source: 'Invoice',
  },
  {
    id: '3',
    date: '2025-01-05',
    description: 'Product Sales',
    amount: 1250.0,
    source: 'E-commerce',
  },
  {
    id: '4',
    date: '2025-01-01',
    description: 'Monthly Retainer - Tech Inc',
    amount: 3000.0,
    source: 'Contract',
  },
]

export const monthlyData = [
  { month: 'Aug', income: 9500, expenses: 6200 },
  { month: 'Sep', income: 11200, expenses: 7100 },
  { month: 'Oct', income: 10800, expenses: 6800 },
  { month: 'Nov', income: 12500, expenses: 7900 },
  { month: 'Dec', income: 14200, expenses: 8500 },
  { month: 'Jan', income: 11750, expenses: 7245 },
]

export const categoryExpenses = [
  { name: 'Food & Dining', value: 1250, fill: 'var(--color-chart-1)' },
  { name: 'Office Expenses', value: 890, fill: 'var(--color-chart-2)' },
  { name: 'Fuel & Commute', value: 650, fill: 'var(--color-chart-3)' },
  { name: 'Software', value: 420, fill: 'var(--color-chart-4)' },
  { name: 'Marketing', value: 1800, fill: 'var(--color-chart-5)' },
  { name: 'Other', value: 2235, fill: 'var(--color-muted)' },
]

export const budgetData = {
  year: '2024-2025',
  totalBudget: 100000,
  spent: 72450,
  categories: [
    { name: 'Marketing', budget: 25000, spent: 18500 },
    { name: 'Operations', budget: 30000, spent: 24200 },
    { name: 'Travel', budget: 15000, spent: 11800 },
    { name: 'Software', budget: 12000, spent: 8950 },
    { name: 'Office', budget: 10000, spent: 6200 },
    { name: 'Miscellaneous', budget: 8000, spent: 2800 },
  ],
}

export const statements = [
  {
    id: '1',
    fileName: 'scotia_jan_2025.pdf',
    uploadDate: '2025-01-20',
    status: 'completed',
    transactions: 45,
  },
  {
    id: '2',
    fileName: 'scotia_dec_2024.pdf',
    uploadDate: '2025-01-05',
    status: 'completed',
    transactions: 52,
  },
  {
    id: '3',
    fileName: 'scotia_nov_2024.pdf',
    uploadDate: '2024-12-10',
    status: 'completed',
    transactions: 38,
  },
]

export const invoices = [
  {
    id: 'INV-001',
    client: 'ABC Corporation',
    email: 'billing@abccorp.com',
    amount: 5000.0,
    status: 'paid',
    issueDate: '2025-01-10',
    dueDate: '2025-01-25',
    paidDate: '2025-01-20',
  },
  {
    id: 'INV-002',
    client: 'XYZ Ltd',
    email: 'accounts@xyzltd.com',
    amount: 2500.0,
    status: 'pending',
    issueDate: '2025-01-15',
    dueDate: '2025-01-30',
    paidDate: null,
  },
  {
    id: 'INV-003',
    client: 'Tech Innovations Inc',
    email: 'finance@techinnovations.com',
    amount: 3750.0,
    status: 'overdue',
    issueDate: '2024-12-20',
    dueDate: '2025-01-05',
    paidDate: null,
  },
  {
    id: 'INV-004',
    client: 'Global Services Co',
    email: 'payments@globalservices.com',
    amount: 1800.0,
    status: 'draft',
    issueDate: '2025-01-22',
    dueDate: '2025-02-06',
    paidDate: null,
  },
  {
    id: 'INV-005',
    client: 'StartUp Ventures',
    email: 'billing@startupventures.io',
    amount: 4200.0,
    status: 'paid',
    issueDate: '2025-01-05',
    dueDate: '2025-01-20',
    paidDate: '2025-01-18',
  },
]

export const contacts = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@abccorp.com',
    phone: '+1 (555) 123-4567',
    address: '123 Business Ave, Toronto, ON M5V 2T6',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.j@xyzltd.com',
    phone: '+1 (555) 234-5678',
    address: '456 Commerce St, Vancouver, BC V6B 1A1',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'mchen@techinnovations.com',
    phone: '+1 (555) 345-6789',
    address: '789 Innovation Blvd, Montreal, QC H3B 2Y5',
  },
  {
    id: '4',
    name: 'Emily Davis',
    email: 'emily.d@globalservices.com',
    phone: '+1 (555) 456-7890',
    address: '321 Enterprise Way, Calgary, AB T2P 3N4',
  },
  {
    id: '5',
    name: 'Robert Wilson',
    email: 'rwilson@startupventures.io',
    phone: '+1 (555) 567-8901',
    address: '654 Startup Lane, Ottawa, ON K1P 5G3',
  },
]

export const calendarEvents = [
  {
    id: '1',
    title: 'Invoice INV-002 Due',
    date: '2025-01-30',
    type: 'invoice',
    amount: 2500.0,
  },
  {
    id: '2',
    title: 'Quarterly Tax Payment',
    date: '2025-01-31',
    type: 'tax',
    amount: 3500.0,
  },
  {
    id: '3',
    title: 'Rent Payment Due',
    date: '2025-02-01',
    type: 'expense',
    amount: 2200.0,
  },
  {
    id: '4',
    title: 'Client Meeting - ABC Corp',
    date: '2025-01-27',
    type: 'meeting',
    amount: null,
  },
  {
    id: '5',
    title: 'Software Subscription Renewal',
    date: '2025-02-05',
    type: 'expense',
    amount: 299.0,
  },
  {
    id: '6',
    title: 'Invoice INV-003 Overdue',
    date: '2025-01-05',
    type: 'overdue',
    amount: 3750.0,
  },
  {
    id: '7',
    title: 'Payroll Processing',
    date: '2025-01-25',
    type: 'expense',
    amount: 8500.0,
  },
  {
    id: '8',
    title: 'Budget Review Meeting',
    date: '2025-01-28',
    type: 'meeting',
    amount: null,
  },
  {
    id: '9',
    title: 'Insurance Premium Due',
    date: '2025-02-10',
    type: 'expense',
    amount: 450.0,
  },
  {
    id: '10',
    title: 'Expected Payment - Tech Inc',
    date: '2025-02-01',
    type: 'income',
    amount: 3000.0,
  },
]
